FROM node:18-alpine

# Создание рабочей директории
WORKDIR /app

# Копирование файлов главного сервера
COPY main-server.js ./
COPY index.html ./

# Экспорт порта
EXPOSE 3000

# Запуск главного сервера
CMD ["node", "main-server.js"] 