openapi: 3.0.0
info:
  title: Swagger Editor
  version: 1.0.0
  description: Welcome to Swagger Editor
paths:
  /hello:
    get:
      summary: Hello World
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello World22dfvfgb2efgsfg"